---
ansible_user: ansible
dns_soa_contact: admin.hannahs.family
firewalld_rules:
  port_node_exporter:
    port: "{{ node_exporter_port }}/tcp"
    state: enabled
node_exporter_port: 9100
node_exporter_web_listen_address: 0.0.0.0:{{ node_exporter_port }}
