---
k3s_manifests_path: templates/k8s_home/manifests/
k3s_metallb_config:
  peers:
    - peer-address: 172.16.0.1
      peer-asn: 64512
      my-asn: 64512
  address-pools:
    - name: public
      protocol: bgp
      auto-assign: false
      addresses:
        - 172.16.1.0/24
    - name: private
      protocol: bgp
      addresses:
        - 172.16.21.0/24
k3s_traefik_enabled: false
k3s_version: v0.5.0
