---
- include_tasks:
    file: debian.yml
    apply:
      become: true
  when: ansible_facts["os_family"] == "Debian"

- include_tasks:
    file: redhat.yml
    apply:
      become: true
  when: ansible_facts["os_family"] == "RedHat"

- include_tasks:
    file: suse.yml
    apply:
      become: true
  when: ansible_facts["os_family"] == "Suse"
