---
all:
  hosts:
    bounsweet:
      ansible_host: 172.16.20.8
    budew:
      ansible_host: 172.16.20.9
    cherubi:
      ansible_host: 172.16.20.10
    deerling:
      ansible_host: 172.16.20.11
    exeggcute:
      ansible_host: 172.16.20.12
    fomantis:
      ansible_host: 172.16.20.13
    rotom:
      ansible_host: 172.16.20.6
    tapu-bulu:
      ansible_host: 104.225.220.45
  children:
    home:
      hosts:
        rotom:
      children:
        raspberry_pi:
          children:
            k8s_home:
              hosts:
                bounsweet:
                  kubernetes_server: true
                budew:
                cherubi:
                deerling:
              children:
                storage:
                  hosts:
                    exeggcute:
                    fomantis:
    vps:
      children:
        k8s:
          hosts:
            tapu-bulu:
              kubernetes_server: true
    debian:
      hosts:
        rotom:
    redhat:
      hosts:
        tapu-bulu:
    suse:
      hosts:
        bounsweet:
        budew:
        cherubi:
        deerling:
        exeggcute:
        fomantis:
