---
all:
  children:
    k8s:
      children:
        k8s-master:
          hosts:
            bounsweet:
            tapu-bulu:
      hosts:
        budew:
        cherubi:
        deerling:
        exeggcute:
        fomantis:
