---
- name: Copy root CA certificate
  become: true
  copy:
    src: ca.cert.pem
    dest: /etc/pki/trust/anchors/hannahs.family.ca.cert.pem
    owner: root
    group: root
    mode: 0644
  notify: Update certificate store
