---
- name: Group hosts by OS family
  group_by:
    key: os_family_{{ ansible_facts["os_family"] }}

- name: Include variables for Kubernetes servers
  include_vars:
    file: k8s_server.yml
  when: kubernetes_server is defined and kubernetes_server
