---
- name: Update RedHat certificate store
  listen: Update certificate store
  become: true
  command: update-ca-trust
  when: ansible_facts["os_family"] == "RedHat"

- name: Update Suse certificate store
  listen: Update certificate store
  become: true
  command: update-ca-certificates
  when: ansible_facts["os_family"] == "Suse"
