---
- hosts: all
  gather_facts: false
  roles:
    - ssh-agent

- hosts: all
  roles:
    - group_by
    - user
    - ca
    - cloudalchemy.node-exporter
    - fail2ban

- hosts: os_family_RedHat:os_family_Suse
  roles:
    - firewalld

- hosts: home:&k8s
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

- hosts: vps:&k8s
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
