---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  roles:
    - ssh

- hosts: all
  roles:
    - ca
    - firewall
    - cloudalchemy.node-exporter

- hosts: k8s
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
