---
- hosts: all
  roles:
    - ca
    - firewall
    - cloudalchemy.node-exporter

- hosts: k8s
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

- hosts: k8s-master
  roles:
    - helm
