---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  roles:
    - ssh

- hosts: all
  roles:
    - group_by
    - user
    - ca
    - cloudalchemy.node-exporter
    - fail2ban

- hosts: os_family_RedHat:os_family_Suse
  roles:
    - firewalld

- hosts: k8s
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
