---
- hosts: all
  gather_facts: false
  roles:
    - ssh-agent

- hosts: all
  roles:
    - group_by
    - hostname
    - packages
    - user
    - ca
  handlers:
    - include: handlers/main.yml

- import_playbook: home.yml

- import_playbook: vps.yml
