---
- name: Open flanneld subnet traffic
  command: /bin/firewall-cmd --direct --add-rule ipv4 filter FORWARD 1
           -i flannel.1 -j ACCEPT -m comment --comment "flannel subnet"
  ignore_errors: true

- name: Save flanneld subnet traffic
  command: /bin/firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 1
           -i flannel.1 -j ACCEPT -m comment --comment "flannel subnet"
  ignore_errors: true

- name: Open flanneld to DNAT'ed traffic
  command: /bin/firewall-cmd --direct --add-rule ipv4 filter FORWARD 1
           -o flannel.1 -j ACCEPT -m comment --comment "flannel subnet"
  ignore_errors: true

- name: Save flanneld to DNAT'ed traffic
  command: /bin/firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 1
           -o flannel.1 -j ACCEPT -m comment --comment "flannel subnet"
  ignore_errors: true

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded
