---
- name: Install firewalld
  become: true
  yum:
    name: firewalld
    state: present

- include_tasks: zones.yml
  when: (firewalld_zones | length) > 0

- name: Configure firewalld rules
  become: true
  firewalld:
    permanent: true
  args: "{{ item.value | from_yaml }}"
  loop: "{{ firewalld_rules | dict2items }}"
  notify: Reload firewalld

- include_tasks:
    file: direct.yml
  when: (firewalld_direct_rules | length) > 0

- name: Enable firewalld
  become: true
  service:
    name: firewalld
    state: started
    enabled: true
